# Generated by Django 6.0.7 on 2026-07-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_apresentacao', models.FileField(blank=True, help_text='Faça o upload do vídeo principal (MP4).', null=True, upload_to='site_media/videos/')),
                ('imagem_fundo', models.ImageField(blank=True, help_text='Imagem de fundo da seção inicial.', null=True, upload_to='site_media/imagens/')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
    ]
