# Generated by Django 6.0.7 on 2026-07-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracaosite'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='opacidade_fundo',
            field=models.FloatField(default=0.92, help_text='Transparência do branco sobre a imagem. Use valores de 0.0 (totalmente transparente) a 1.0 (totalmente branco). Ex: 0.92 ou 0.85'),
        ),
    ]
