# Generated by Django 6.0.7 on 2026-07-15 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='alternativa',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='teste',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='questao',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='tentativa',
        ),
        migrations.RemoveField(
            model_name='tentativa',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='tentativa',
            name='teste',
        ),
        migrations.RemoveField(
            model_name='tentativa',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Alternativa',
        ),
        migrations.DeleteModel(
            name='Questao',
        ),
        migrations.DeleteModel(
            name='Resposta',
        ),
        migrations.DeleteModel(
            name='Teste',
        ),
        migrations.DeleteModel(
            name='Tentativa',
        ),
    ]
