# Generated by Django 6.0.7 on 2026-07-10 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Instituição')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='accounts.escola', verbose_name='Escola'),
        ),
    ]
