# Generated by Django 6.0.7 on 2026-07-18 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_escola_alter_usuario_escola'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCLEAceite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceito', models.BooleanField(default=False)),
                ('data_aceite', models.DateTimeField(auto_now_add=True)),
                ('ip_aceite', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tcle_aceite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
