# Generated by Django 6.0.7 on 2026-07-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tcleaceite'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_surdo',
            field=models.BooleanField(default=True, verbose_name='É surdo(a)?'),
        ),
    ]
