# Generated by Django 6.0.7 on 2026-07-09 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ordem', models.IntegerField(default=1, verbose_name='Ordem de Exibição')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='modulos.modulo')),
            ],
        ),
        migrations.CreateModel(
            name='Videoaula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('url_video', models.URLField(verbose_name='URL do Vídeo (YouTube)')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('duracao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Duração')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videoaulas', to='modulos.modulo')),
            ],
        ),
    ]
