# Generated by Django 6.0.7 on 2026-07-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoaula',
            name='url_video',
        ),
        migrations.AddField(
            model_name='modulo',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas/', verbose_name='Imagem de Capa'),
        ),
        migrations.AddField(
            model_name='videoaula',
            name='ordem',
            field=models.PositiveIntegerField(default=1, verbose_name='Ordem de Exibição'),
        ),
        migrations.AddField(
            model_name='videoaula',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbs/', verbose_name='Miniatura (Thumbnail)'),
        ),
        migrations.AddField(
            model_name='videoaula',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Arquivo de Vídeo'),
        ),
        migrations.AlterField(
            model_name='videoaula',
            name='duracao',
            field=models.DurationField(blank=True, null=True, verbose_name='Duração (HH:MM:SS)'),
        ),
    ]
