# Generated by Django 6.0.7 on 2026-07-13 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_remove_videoaula_url_video_modulo_imagem_capa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluida', models.BooleanField(default=False)),
                ('ultimo_acesso', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos_aulas', to=settings.AUTH_USER_MODEL)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.videoaula')),
            ],
            options={
                'verbose_name': 'Progresso de Aula',
                'verbose_name_plural': 'Progressos de Aulas',
                'unique_together': {('aluno', 'aula')},
            },
        ),
    ]
