# Generated by Django 6.0.7 on 2026-07-14 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0003_progressoaula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='tipo',
            field=models.CharField(choices=[('PRE', 'Pré-teste'), ('POS', 'Pós-teste'), ('EXERCICIO', 'Exercício de Fixação')], default='EXERCICIO', max_length=15),
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(verbose_name='Enunciado da Questão')),
                ('imagem_apoio', models.ImageField(blank=True, null=True, upload_to='perguntas/', verbose_name='Imagem de Apoio (Opcional)')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='modulos.atividade')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, verbose_name='Texto da Alternativa')),
                ('is_correta', models.BooleanField(default=False, verbose_name='É a resposta correta?')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='modulos.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('alternativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.alternativa')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_atividades', to=settings.AUTH_USER_MODEL)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.pergunta')),
            ],
            options={
                'unique_together': {('aluno', 'pergunta')},
            },
        ),
    ]
