# Generated by Django 6.0.7 on 2026-07-14 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0004_atividade_tipo_pergunta_alternativa_respostaaluno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='tipo_pergunta',
            field=models.CharField(choices=[('MULTIPLA', 'Múltipla Escolha'), ('ASSOC', 'Associação (Ligar Colunas)')], default='MULTIPLA', max_length=15, verbose_name='Tipo de Questão'),
        ),
        migrations.CreateModel(
            name='ItemAssociacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coluna_a', models.CharField(max_length=255, verbose_name='Item Esquerdo (Fixo)')),
                ('coluna_b', models.CharField(max_length=255, verbose_name='Item Direito (Correspondente Correto)')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_associacao', to='modulos.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaAssociacaoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_aluno_coluna_b', models.CharField(max_length=255)),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_associacao', to=settings.AUTH_USER_MODEL)),
                ('item_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.itemassociacao')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.pergunta')),
            ],
            options={
                'unique_together': {('aluno', 'item_a')},
            },
        ),
    ]
