# Generated by Django 6.0.7 on 2026-07-15 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0005_pergunta_tipo_pergunta_itemassociacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='modulos.modulo'),
        ),
    ]
