# Generated by Django 6.0.7 on 2026-07-19 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0006_alter_atividade_modulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressoaula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progressos_aulas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='progressoaula',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modulos.videoaula'),
        ),
        migrations.AlterField(
            model_name='respostaaluno',
            name='alternativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modulos.alternativa'),
        ),
        migrations.AlterField(
            model_name='respostaaluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas_atividades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='respostaaluno',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modulos.pergunta'),
        ),
        migrations.AlterField(
            model_name='respostaassociacaoaluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas_associacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='respostaassociacaoaluno',
            name='item_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modulos.itemassociacao'),
        ),
        migrations.AlterField(
            model_name='respostaassociacaoaluno',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modulos.pergunta'),
        ),
    ]
