# Generated by Django 6.0.7 on 2026-07-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0007_alter_progressoaula_aluno_alter_progressoaula_aula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativa (Visível na prova?)'),
        ),
        migrations.AddField(
            model_name='videoaula',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativa (Visível para os alunos?)'),
        ),
    ]
