# Generated by Django 6.0.7 on 2026-08-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0008_pergunta_is_active_videoaula_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativa',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativa?'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativa (Visível para os alunos?)'),
        ),
        migrations.AddField(
            model_name='itemassociacao',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativa?'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo (Visível para os alunos?)'),
        ),
    ]
